import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as readline from "node:readline/promises";
import { evidenceLine } from "./render.js";
import type {
  CandidateGap,
  IntelConfig,
  IntelRunOptions,
  IssueResult,
  RenderInput,
} from "./types.js";

const FINGERPRINT_MARKER = "oma-intel-fingerprint";

function issueFingerprint(
  config: IntelConfig,
  accepted: CandidateGap[],
): string {
  const seed = [
    config.target,
    ...accepted.map((candidate) => candidate.capability).sort(),
  ].join("|");
  return createHash("sha256").update(seed).digest("hex").slice(0, 16);
}

function buildIssuePlan(result: RenderInput): {
  title: string;
  body: string;
  fingerprint: string;
} {
  const accepted = result.candidates.filter((c) => c.decision === "accept");
  const rejected = result.candidates.filter((c) => c.decision !== "accept");
  const fingerprint = issueFingerprint(result.config, accepted);
  const lead =
    accepted[0]?.capability ?? rejected[0]?.capability ?? "intelligence";
  const title = `intel: ${lead} opportunities for ${result.config.target}`;
  const body = [
    `<!-- ${FINGERPRINT_MARKER}: ${fingerprint} -->`,
    "",
    "## Summary",
    "",
    accepted.length > 0
      ? `Adversarial review accepted ${accepted.length} candidate(s) from the latest intelligence run on \`${result.config.target}\`.`
      : "No candidate passed the adversarial gates; filing as a watch list.",
    "",
    "## Accepted candidates",
    "",
    ...(accepted.length > 0
      ? accepted.map(
          (candidate) =>
            `- ${candidate.title} (value ${candidate.valueScore}/100, ${candidate.capability})`,
        )
      : ["- None"]),
    "",
    "## Rejected / deferred",
    "",
    ...(rejected.length > 0
      ? rejected
          .slice(0, 10)
          .map((candidate) => `- ${candidate.title} - ${candidate.decision}`)
      : ["- None"]),
    "",
    "## Provenance",
    "",
    ...result.candidates
      .flatMap((candidate) => candidate.evidence)
      .slice(0, 15)
      .map(evidenceLine),
    "",
    "_Generated by `oma intel`. External evidence is quoted as untrusted data._",
  ].join("\n");
  return { title, body, fingerprint };
}

function gh(args: string[], input?: string): string {
  return execFileSync("gh", args, {
    encoding: "utf-8",
    input,
    stdio: ["pipe", "pipe", "pipe"],
  }).trim();
}

function ghAvailable(): boolean {
  try {
    gh(["--version"]);
    gh(["auth", "status"]);
    return true;
  } catch {
    return false;
  }
}

function findDuplicateIssue(
  repo: string,
  fingerprint: string,
): { number: number; url: string } | undefined {
  try {
    const raw = gh([
      "issue",
      "list",
      "--repo",
      repo,
      "--state",
      "all",
      "--search",
      fingerprint,
      "--json",
      "number,url,body",
      "--limit",
      "30",
    ]);
    const parsed = JSON.parse(raw || "[]") as Array<Record<string, unknown>>;
    const match = parsed.find(
      (issue) =>
        typeof issue.body === "string" && issue.body.includes(fingerprint),
    );
    if (match && typeof match.number === "number") {
      return { number: match.number, url: String(match.url ?? "") };
    }
  } catch {
    // Search failures degrade to "no known duplicate" rather than blocking.
  }
  return undefined;
}

async function confirmInteractive(question: string): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  try {
    const answer = (await rl.question(`${question} [y/N] `))
      .trim()
      .toLowerCase();
    return answer === "y" || answer === "yes";
  } finally {
    rl.close();
  }
}

export async function createGitHubIssue(
  result: RenderInput,
  options: IntelRunOptions,
): Promise<IssueResult> {
  const { title, body, fingerprint } = buildIssuePlan(result);
  const dryRun = !!options.dryRun;
  const remote = result.config.remote.githubIssue;
  const repo = remote.repo ?? options.baseRepo?.trim() ?? result.config.target;

  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repo)) {
    return {
      status: "refused",
      detail: `Cannot file an issue: target "${repo}" is not an owner/name GitHub repo. Pass --base-repo.`,
      title,
      fingerprint,
      body,
    };
  }

  if (dryRun) {
    return {
      status: "dry-run",
      detail: remote.enabled
        ? `Would create an issue in ${repo}. Body printed below.`
        : `Preview only: issue creation is disabled in config. Body printed below.`,
      title,
      fingerprint,
      body,
    };
  }

  if (!remote.enabled) {
    return {
      status: "refused",
      detail:
        "Issue creation is disabled. Set remote.github_issue.enabled: true in config.",
      title,
      fingerprint,
      body,
    };
  }

  if (!ghAvailable()) {
    return {
      status: "refused",
      detail:
        "GitHub CLI (gh) is not installed or not authenticated. Run `gh auth login`.",
      title,
      fingerprint,
      body,
    };
  }

  const duplicate = findDuplicateIssue(repo, fingerprint);
  const interactive = !!process.stdin.isTTY;

  if (duplicate) {
    if (!interactive && !options.assumeYes) {
      return {
        status: "duplicate",
        detail: `Matching issue #${duplicate.number} already exists (${duplicate.url}). Re-run with --yes to file anyway.`,
        title,
        fingerprint,
        url: duplicate.url,
        body,
      };
    }
    if (
      interactive &&
      !(await confirmInteractive(
        `A matching issue (#${duplicate.number}) already exists. Create another?`,
      ))
    ) {
      return {
        status: "skipped",
        detail: `Skipped: duplicate of #${duplicate.number} (${duplicate.url}).`,
        title,
        fingerprint,
        url: duplicate.url,
        body,
      };
    }
  }

  if (remote.requireConfirm) {
    if (!interactive && !options.assumeYes) {
      return {
        status: "refused",
        detail:
          "Issue creation requires confirmation. In non-interactive mode pass --yes to approve.",
        title,
        fingerprint,
        body,
      };
    }
    if (
      interactive &&
      !options.assumeYes &&
      !(await confirmInteractive(`Create issue "${title}" in ${repo}?`))
    ) {
      return {
        status: "skipped",
        detail: "Issue creation declined.",
        title,
        fingerprint,
        body,
      };
    }
  }

  try {
    const url = gh(
      ["issue", "create", "--repo", repo, "--title", title, "--body-file", "-"],
      body,
    );
    return {
      status: "created",
      detail: `Created issue in ${repo}.`,
      title,
      fingerprint,
      url: url || undefined,
      body,
    };
  } catch (error) {
    return {
      status: "refused",
      detail: `gh issue create failed: ${error instanceof Error ? error.message : String(error)}`,
      title,
      fingerprint,
      body,
    };
  }
}
