// AUTO-GENERATED by cli/scripts/generate-skill-data.mjs. Do not edit by hand.
// Source: .agents/skills/*/SKILL.md frontmatter.
import type { SkillsRegistry } from "../types/index.js";

export const SKILLS: SkillsRegistry = {
  domain: [
    {
      name: "oma-architecture",
      desc: `Architecture specialist for software/system design, module and service boundaries, tradeoff analysis, and stakeholder synthesis. Uses context-aware methods such as diagnostic routing, design-twice comparison, ATAM-style risk analysis, CBAM-style prioritization, and ADR-style decision records.`,
    },
    {
      name: "oma-backend",
      desc: `Backend specialist for APIs, databases, authentication with clean architecture (Repository/Service/Router pattern). Use for API, endpoint, REST, database, server, migration, and auth work.`,
    },
    {
      name: "oma-db",
      desc: `Database specialist for SQL, NoSQL, and vector database modeling, schema design, normalization, indexing, transactions, integrity, concurrency control, backup, capacity planning, data standards, anti-pattern review, and compliance-aware database design. Use for database, schema, ERD, table design, document model, vector index design, RAG retrieval architecture, migration, query tuning, glossary, capacity estimation, backup strategy, database anti-pattern remediation work, and ISO 27001, ISO 27002, or ISO 22301-aware database recommendations.`,
    },
    {
      name: "oma-frontend",
      desc: `Frontend specialist for React, Next.js, TypeScript with FSD-lite architecture, shadcn/ui, and design system alignment. Use for UI, component, page, layout, CSS, Tailwind, and shadcn work.`,
    },
    {
      name: "oma-mobile",
      desc: `Mobile specialist for Flutter, React Native, and Swift native iOS development. Use for mobile app, Flutter, Dart, React Native, Swift, SwiftUI, iOS, Android, Riverpod, swift-openapi-generator, and widget work.`,
    },
  ],
  design: [
    {
      name: "oma-design",
      desc: `AI design specialist skill with DESIGN.md management, anti-pattern enforcement, optional Stitch MCP integration, and component library guidance. Covers typography, color systems, motion design (motion/react, GSAP, Three.js), responsive-first layouts, and accessibility (WCAG 2.2).`,
    },
  ],
  coordination: [
    {
      name: "oma-brainstorm",
      desc: `Design-first ideation that explores user intent, constraints, and approaches before any planning or implementation. Use for brainstorming, ideation, exploring concepts, and evaluating approaches.`,
    },
    {
      name: "oma-coordination",
      desc: `Guide for coordinating PM, Frontend, Backend, Mobile, and QA agents on complex projects via CLI. Use for manual step-by-step coordination and workflow guidance.`,
    },
    {
      name: "oma-orchestrator",
      desc: `Automated multi-agent orchestrator that spawns CLI subagents in parallel, coordinates via MCP Memory, and monitors progress. Use for orchestration, parallel execution, and automated multi-agent workflows.`,
    },
    {
      name: "oma-pm",
      desc: `Product manager that decomposes requirements into actionable tasks with priorities and dependencies. Use for planning, requirements, specification, scope, prioritization, task breakdown, and ISO 21500, ISO 31000, or ISO 38500-aligned planning recommendations.`,
    },
    {
      name: "oma-qa",
      desc: `Quality assurance specialist for security, performance, accessibility, comprehensive testing, and quality standard alignment. Use for test, review, security audit, OWASP, coverage, lint work, and ISO/IEC 25010 or ISO/IEC 29119-aligned QA recommendations.`,
    },
  ],
  utility: [
    {
      name: "oma-academic-writer",
      desc: `Academic writing specialist for publication-grade English prose. Drafts, revises, and audits essays, reports, analysis sections, executive summaries, conclusions, and literature reviews while enforcing sentence-structure variation, high-frequency academic verbs, calibrated hedging, and anti-AI stylistic compliance. USE for academic writing, essay polish, paragraph rewrite, prose revision against any rubric tier (HD/D/C, A/B/C, top-band/mid-band, etc.), anti-AI audit, reverse outlining, claim-evidence mapping, and rubric enforcement on assignments.`,
    },
    {
      name: "oma-debug",
      desc: `Bug diagnosis and fixing specialist - analyzes errors, identifies root causes, provides fixes, and writes regression tests. Use for bug, debug, error, crash, traceback, exception, and regression work.`,
    },
    {
      name: "oma-deepsec",
      desc: `Drive Vercel's \`deepsec\` agent-powered vulnerability scanner end-to-end: installing the \`.deepsec/\` workspace, bootstrapping \`INFO.md\`, running cost-aware \`scan\` / \`process\` / \`triage\` / \`revalidate\` / \`export\` passes, gating PRs with \`process --diff\`, writing custom matchers, and triaging findings. Use whenever the user mentions deepsec, asks an agent to scan a repo for vulnerabilities, runs into \`pnpm deepsec\` / \`bunx deepsec\` commands, wants a CI-based PR security review, sees a \`.deepsec/\` directory, or asks about \`INFO.md\` / matchers / \`process --diff\` / \`revalidate\`, even when the tool name is not spoken. Deepsec scans are expensive (a single full scan can cost hundreds to tens of thousands of dollars) so the skill exists in part to keep the user from getting surprised.`,
    },
    {
      name: "oma-docs",
      desc: `Verify documentation references against the current codebase and propose updates for diff-affected docs. Use to check if docs still match reality (broken file paths, CLI commands, config keys, env vars, scripts) and to surface docs that may need updating after code changes.`,
    },
    {
      name: "oma-hwp",
      desc: `Convert HWP / HWPX / HWPML files to Markdown using kordoc. Extracts text, headings, tables, lists, images, footnotes, and hyperlinks. Use for Korean word processor files (Hangul), government documents, and AI-ready data preparation.`,
    },
    {
      name: "oma-image",
      desc: `Multi-vendor AI image generation with authentication-aware parallel dispatch. Routes to Codex (gpt-image-2 via ChatGPT OAuth), Antigravity (gemini-2.5-flash-image aka nano-banana via \`agy\` CLI + Gemini Code Assist), and Pollinations (flux/zimage, free with signup). Use for image generation, image creation, visual asset generation, and AI art.`,
    },
    {
      name: "oma-market",
      desc: `Market research skill for pain-point extraction, trend detection, competitor positioning, and discovery across community sources (Reddit, HN, Bluesky, Mastodon, GitHub Issues, web). Routes via oma-search transport, deterministic CLI compute, intent-auto SWOT/Porter's 5F/PESTEL frameworks. Use for market research, pain point analysis, trend detection, competitor research, user complaints, voice-of-customer, 시장조사, 사용자 페인, 트렌드, 경쟁구도.`,
    },
    {
      name: "oma-pdf",
      desc: `Convert PDF files to Markdown using opendataloader-pdf. Extracts text, tables, headings, lists, and images with correct reading order. Use for PDF parsing, PDF to Markdown conversion, document extraction, and AI-ready data preparation.`,
    },
    {
      name: "oma-recap",
      desc: `Analyze conversation histories from multiple AI tools (Grok, Claude, Codex, Qwen, Cursor, Antigravity) and generate themed daily/period work summaries. Filter by date or time window.`,
    },
    {
      name: "oma-scholar",
      desc: `Scholarly research companion using Knows sidecar spec (.knows.yaml). Generates, validates, reviews, queries, and compares structured research-paper sidecars, and fetches them from knows.academy. Use for academic literature search, survey synthesis, paper authoring assistance, and peer review with token-efficient claim/evidence/relation access.`,
    },
    {
      name: "oma-scm",
      desc: `SCM (software configuration management) and Git: branching, merges, conflicts, worktrees, baselines, audit readiness, plus Conventional Commits and safe staging.`,
    },
    {
      name: "oma-search",
      desc: `Intent-based search router with trust scoring. Routes queries to optimal channels (Context7 docs, native web search, gh/glab code search, Serena local) and attaches domain trust labels. Use for search, find, lookup, reference, docs, code search, and web research.`,
    },
    {
      name: "oma-skill-creator",
      desc: `Create or update OMA skills in the SSL-lite human-readable format. Use when adding a new \`.agents/skills/{skill-name}/SKILL.md\`, converting an existing skill to the standardized Scheduling / Structural Flow / Logical Operations / References structure, or validating whether a skill has enough routing, execution, resource, and safety detail.`,
    },
    {
      name: "oma-slide",
      desc: `HTML presentation deck generator and multi-format exporter. Generates distinctive, animation-rich HTML decks at a fixed 1920×1080 stage, then deterministically validates, bundles, and exports them to PDF/PNG/PPTX via the \`oma slide\` CLI. Use for slide, deck, presentation, slides, pptx, keynote, 슬라이드, 발표자료, プレゼン, 幻灯片 requests. Produces self-contained single-file HTML with keyboard/touch nav, speaker notes, and print-to-PDF support.`,
    },
    {
      name: "oma-translator",
      desc: `Context-aware translation that preserves tone, style, and natural word order. Use when translating UI strings, documentation, marketing copy, or any multilingual content. Infers register, domain, and style from the source text and surrounding codebase context.`,
    },
    {
      name: "oma-video",
      desc: `Short-form, explainer, and demo video generation via a key-optional 3-tier router. Composes scripts, oma-voice narration, oma-image/oma-slide/stock visuals, key-free captions, and a vendored Remotion compositor into reproducible run directories. Routes three modes — shorts/reels (9:16), explainer (16:9 README/code/data), and demo/walkthrough (screen capture, incl. supervised headed web-app capture of any URL). Use for video, shorts, reels, short-form, demo, explainer, walkthrough, screencast, web capture, video generation, 영상, 숏폼, 쇼츠, 릴스, 데모, 설명 영상.`,
    },
    {
      name: "oma-voice",
      desc: `Local-first text-to-speech and speech-to-text via the Voicebox MCP server. Generates speech from cloned or preset voice profiles for agent notifications, content voiceovers, and audio asset creation, and transcribes audio files for meeting notes or memos. Runs entirely on-device with no cloud, no API keys, no per-call cost. Use for voice generation, TTS, STT, transcription, voiceover, narration, dictation, audio asset work.`,
    },
  ],
  infrastructure: [
    {
      name: "oma-dev-workflow",
      desc: `Use when setting up or optimizing developer workflows in a monorepo, managing mise tasks, git hooks, CI/CD pipelines, database migrations, or release automation. Invoke for development environment setup, build automation, testing workflows, and release coordination.`,
    },
    {
      name: "oma-observability",
      desc: `Intent-based observability + traceability router across layers, boundaries, and signals. Routes to vendor-specific skills via category taxonomy; owns transport tuning, meta-observability, incident forensics. Use for observability, traceability, telemetry, APM, RUM, metrics, logs, traces, profiles, SLO, incident forensics, tracing architecture work.`,
    },
    {
      name: "oma-tf-infra",
      desc: `Infrastructure-as-code specialist for multi-cloud provisioning using Terraform across any provider (AWS, GCP, Azure, Oracle Cloud). Use for terraform plan/apply, state management, compute, databases, storage, networking, IAM, OIDC, cost optimization, policy-as-code, ISO/IEC 42001 AI controls, ISO 22301 continuity, and ISO/IEC/IEEE 42010 architecture documentation.`,
    },
  ],
};

export const PRESETS: Record<string, string[]> = {
  fullstack: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-backend",
    "oma-mobile",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-tf-infra",
    "oma-dev-workflow",
  ],
  "fullstack-web": [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  "fullstack-mobile": [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-mobile",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  frontend: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  backend: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  mobile: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-mobile",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  devops: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-tf-infra",
    "oma-dev-workflow",
    "oma-observability",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  research: [
    "oma-scholar",
    "oma-market",
    "oma-pdf",
    "oma-hwp",
    "oma-academic-writer",
    "oma-search",
    "oma-translator",
    "oma-scm",
  ],
  content: [
    "oma-design",
    "oma-image",
    "oma-voice",
    "oma-academic-writer",
    "oma-translator",
    "oma-scm",
  ],
  all: [
    ...SKILLS.domain,
    ...SKILLS.design,
    ...SKILLS.coordination,
    ...SKILLS.utility,
    ...SKILLS.infrastructure,
  ].map((s) => s.name),
};
