/**
 * Doctor check — oma-hook.sh binary resolvability (design 019 §T1-d).
 *
 * For each hook-model vendor, if `<projectDir>/<hookDir>/oma-hook.sh` is
 * present the check verifies that the oma binary is resolvable the same
 * way the wrapper does at runtime:
 *
 *   1. `command -v oma` on the current PATH (PATH lookup via executableSearchPaths)
 *   2. The recorded absolute path embedded in the wrapper (exists + executable)
 *
 * Possible outcomes per vendor:
 *   - "skip"    — wrapper not installed (vendor not set up); check is silent / N/A.
 *   - "pass"    — oma is resolvable; hook will dispatch correctly.
 *   - "warning" — oma is NOT resolvable; reports advisory with remediation.
 *
 * Fail-open: this is a WARNING, never a hard error — the wrapper itself
 * exits 0 when oma is missing so the agent is never blocked.
 */

import {
  accessSync,
  existsSync,
  constants as fsConstants,
  readFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

// ---------------------------------------------------------------------------
// Vendor → hookDir table (mirrors .agents/hooks/variants/*.json hookDir field)
// Project-scoped vendors only; antigravity is HOME-scoped (handled separately).
// ---------------------------------------------------------------------------

const PROJECT_HOOK_DIRS: Array<{ vendor: string; hookDir: string }> = [
  { vendor: "claude", hookDir: ".claude/hooks" },
  { vendor: "codex", hookDir: ".codex/hooks" },
  { vendor: "cursor", hookDir: ".cursor/hooks" },
  { vendor: "gemini", hookDir: ".gemini/hooks" },
  { vendor: "grok", hookDir: ".grok/hooks" },
  { vendor: "kiro", hookDir: ".kiro/hooks" },
  { vendor: "qwen", hookDir: ".qwen/hooks" },
];

/** Antigravity writes to HOME rather than the project dir. */
const ANTIGRAVITY_HOOK_DIR = ".gemini/antigravity-cli/hooks";

/** Filename written by generateOmaHookWrapper / installHooksFromVariant. */
const OMA_HOOK_WRAPPER_FILENAME = "oma-hook.sh";

// ---------------------------------------------------------------------------
// Binary resolution helpers (mirrors the wrapper's own resolution strategy)
// ---------------------------------------------------------------------------

function canExecute(filePath: string): boolean {
  try {
    accessSync(filePath, fsConstants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function executableSearchPaths(env: NodeJS.ProcessEnv): string[] {
  const home = homedir();
  return [
    ...(env.PATH ?? "").split(":"),
    join(home, ".bun", "bin"),
    join(home, ".local", "bin"),
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ].filter((p, i, arr) => p && arr.indexOf(p) === i);
}

/** True when `oma` is found on the current PATH. */
function omaOnPath(env: NodeJS.ProcessEnv): boolean {
  for (const dir of executableSearchPaths(env)) {
    const candidate = join(dir, "oma");
    if (existsSync(candidate) && canExecute(candidate)) return true;
  }
  return false;
}

/**
 * Extract the recorded absolute oma path from an oma-hook.sh wrapper.
 *
 * The wrapper generated by `generateOmaHookWrapper` contains:
 *   elif [ -x "<recordedPath>" ]; then
 *
 * We match that line to recover the path written at install time.
 * Returns null if the wrapper doesn't contain the expected pattern
 * (e.g. it's an older wrapper or has been modified).
 */
function extractRecordedPath(wrapperContent: string): string | null {
  const match = wrapperContent.match(/\[ -x "([^"]+)" \]/);
  return match?.[1] ?? null;
}

/** True when the recorded install-time path still exists and is executable. */
function recordedPathResolvable(wrapperPath: string): boolean {
  let content: string;
  try {
    content = readFileSync(wrapperPath, "utf-8");
  } catch {
    return false;
  }
  const recorded = extractRecordedPath(content);
  if (!recorded) return false;
  return existsSync(recorded) && canExecute(recorded);
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type HookWrapperCheckStatus = "skip" | "pass" | "warning";

export interface HookWrapperCheck {
  vendor: string;
  wrapperPath: string;
  status: HookWrapperCheckStatus;
  /** Human-readable remediation hint, present when status === "warning". */
  remediation?: string;
}

// ---------------------------------------------------------------------------
// Per-vendor check
// ---------------------------------------------------------------------------

function checkWrapper(
  vendor: string,
  wrapperPath: string,
  env: NodeJS.ProcessEnv,
): HookWrapperCheck {
  if (!existsSync(wrapperPath)) {
    return { vendor, wrapperPath, status: "skip" };
  }

  const resolvable = omaOnPath(env) || recordedPathResolvable(wrapperPath);
  if (resolvable) {
    return { vendor, wrapperPath, status: "pass" };
  }

  return {
    vendor,
    wrapperPath,
    status: "warning",
    remediation: "Run 'oma link' to regenerate the hook wrapper",
  };
}

// ---------------------------------------------------------------------------
// Public collector
// ---------------------------------------------------------------------------

/**
 * Collect oma-hook.sh resolvability checks for all hook-model vendors.
 *
 * @param projectDir - The project root (process.cwd() in normal usage).
 * @param env - Process environment; defaults to `process.env`.
 *   Override in tests to control PATH and env vars.
 */
export function collectHookWrapperChecks(
  projectDir: string,
  env: NodeJS.ProcessEnv = process.env,
): HookWrapperCheck[] {
  const checks: HookWrapperCheck[] = [];

  // Project-scoped vendors
  for (const { vendor, hookDir } of PROJECT_HOOK_DIRS) {
    const wrapperPath = join(
      projectDir,
      ...hookDir.split("/"),
      OMA_HOOK_WRAPPER_FILENAME,
    );
    checks.push(checkWrapper(vendor, wrapperPath, env));
  }

  // Antigravity: HOME-scoped
  const agy = (() => {
    const wrapperPath = join(
      homedir(),
      ...ANTIGRAVITY_HOOK_DIR.split("/"),
      OMA_HOOK_WRAPPER_FILENAME,
    );
    return checkWrapper("antigravity", wrapperPath, env);
  })();
  checks.push(agy);

  return checks;
}
