import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
  parseFrontmatter,
  serializeFrontmatter,
} from "../utils/frontmatter.js";

/** SSOT for all rules. */
export const RULES_DIR = ".agents/rules";

const CURSOR_RULES_DIR = ".cursor/rules";
const CLAUDE_RULES_DIR = ".claude/rules";

interface ParsedRule {
  name: string;
  description: string;
  globs: string;
  alwaysApply: boolean;
  body: string;
}

/** Read and parse all .md rule files from the SSOT directory. */
export function readRules(baseDir: string): ParsedRule[] {
  const rulesDir = join(baseDir, RULES_DIR);
  if (!existsSync(rulesDir)) return [];

  return readdirSync(rulesDir)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const content = readFileSync(join(rulesDir, file), "utf-8");
      const { frontmatter, body } = parseFrontmatter(content);
      return {
        name: file.replace(".md", ""),
        description:
          (frontmatter.description as string) || file.replace(".md", ""),
        globs: (frontmatter.globs as string) || "",
        alwaysApply: (frontmatter.alwaysApply as boolean) || false,
        body: body.trim(),
      };
    });
}

// =============================================================================
// Cursor (.cursor/rules/*.mdc)
// =============================================================================

/**
 * Generate .cursor/rules/*.mdc from SSOT.
 * Cursor uses: description, globs, alwaysApply frontmatter.
 */
export function applyCursorRules(targetDir: string): string[] {
  const rules = readRules(targetDir);
  if (rules.length === 0) return [];

  const cursorDir = join(targetDir, CURSOR_RULES_DIR);
  mkdirSync(cursorDir, { recursive: true });

  const exported: string[] = [];

  for (const rule of rules) {
    const header = `<!-- Generated by oh-my-agent. Source: ${RULES_DIR}/${rule.name}.md -->`;
    const content = [
      "---",
      `description: ${JSON.stringify(rule.description)}`,
      `globs: ${rule.globs ? JSON.stringify(rule.globs) : ""}`,
      `alwaysApply: ${rule.alwaysApply}`,
      "---",
      "",
      header,
      "",
      rule.body,
      "",
    ].join("\n");

    writeFileSync(join(cursorDir, `${rule.name}.mdc`), content);
    exported.push(rule.name);
  }

  return exported;
}

// =============================================================================
// Claude Code (.claude/rules/*.md)
// =============================================================================

/**
 * Generate .claude/rules/*.md from SSOT.
 * Claude Code uses: paths (mapped from globs) frontmatter.
 */
export function generateClaudeRules(targetDir: string): string[] {
  const rules = readRules(targetDir);
  if (rules.length === 0) return [];

  const claudeDir = join(targetDir, CLAUDE_RULES_DIR);
  mkdirSync(claudeDir, { recursive: true });

  const exported: string[] = [];

  for (const rule of rules) {
    const fm: Record<string, unknown> = {
      description: rule.description,
    };

    if (!rule.alwaysApply && rule.globs) {
      fm.paths = rule.globs;
    }

    const content = serializeFrontmatter(fm, `\n${rule.body}\n`);
    writeFileSync(join(claudeDir, `${rule.name}.md`), content);
    exported.push(rule.name);
  }

  return exported;
}

// =============================================================================
// Raw copy (SSOT → SSOT in target)
// =============================================================================

export function installRulesRaw(sourceDir: string, targetDir: string): void {
  const src = join(sourceDir, RULES_DIR);
  if (!existsSync(src)) return;

  const dest = join(targetDir, RULES_DIR);
  mkdirSync(dest, { recursive: true });
  cpSync(src, dest, { recursive: true, force: true });
}

// =============================================================================
// Single-file vendors (GEMINI.md, AGENTS.md)
// — Usage guide + Rules index combined in one OMA block
// — AGENTS.md: Codex (native) + Qwen (native since 2026-03) + Cursor (native)
// — GEMINI.md: Gemini CLI only (does not read AGENTS.md by default)
// =============================================================================

const OMA_START =
  "<!-- OMA:START — managed by oh-my-agent. Do not edit this block manually. -->";
const OMA_END = "<!-- OMA:END -->";

/**
 * Vendor → target file mapping.
 * codex/qwen/cursor share AGENTS.md (all read it natively).
 * claude uses project-local CLAUDE.md.
 * gemini requires its own GEMINI.md (default context filename).
 */
const VENDOR_FILES: Record<string, string> = {
  claude: "CLAUDE.md",
  gemini: "GEMINI.md",
  codex: "AGENTS.md",
  cursor: "AGENTS.md",
  qwen: "AGENTS.md",
  pi: "AGENTS.md",
};

/** Vendor-specific subagent spawn instructions. */
const VENDOR_SPAWN: Record<string, string> = {
  claude:
    "Same-vendor native dispatch via Claude Code Agent tool with `.claude/agents/{name}.md`; cross-vendor fallback via `oma agent:spawn`",
  gemini:
    "Same-vendor native dispatch via `.gemini/agents/{name}.md`; cross-vendor or unsupported cases fall back to `oma agent:spawn {agent} {prompt} {sessionId}`",
  cursor: "`@agent-name` (defined in `.cursor/agents/`)",
  codex:
    "Same-vendor native dispatch via Codex custom agents in `.codex/agents/{name}.toml`; cross-vendor fallback via `oma agent:spawn`",
  qwen: "`oma agent:spawn {agent} {prompt} {sessionId}`",
  pi: "pi has no native subagent API; use `oma agent:spawn {agent} {prompt} {sessionId} -m pi` for CLI subprocess dispatch",
};

/** Vendor-specific hook info. */
const VENDOR_HOOKS: Record<string, string> = {
  claude:
    "Hooks: `UserPromptSubmit` (keyword detection), `PreToolUse`, `Stop` (persistent mode)",
  gemini:
    "Hooks: `BeforeAgent` (keyword detection), `BeforeTool`, `AfterAgent` (persistent mode)",
  codex:
    "Hooks: `UserPromptSubmit` (keyword detection), `PreToolUse`, `Stop` (persistent mode)",
  cursor:
    "Hooks: `UserPromptSubmit` / `beforeSubmitPrompt` (keyword detection)",
  qwen: "Hooks: `UserPromptSubmit` (keyword detection), `PreToolUse`, `Stop` (persistent mode)",
  pi: "Extension bridge: `.pi/extensions/oma/index.ts` maps `before_agent_start` and `tool_call` to OMA hook scripts",
};

/**
 * Build a combined OMA block (usage guide + rules index) for a vendor.
 */
function buildVendorBlock(vendor: string, rules: ParsedRule[]): string {
  const lines = [
    OMA_START,
    "",
    "# oh-my-agent",
    "",
    "## Architecture",
    "",
    "- **SSOT**: `.agents/` directory (do not modify directly)",
    "- **Response language**: Follows `language` in `.agents/oma-config.yaml`",
    "- **Skills**: `.agents/skills/` (domain specialists)",
    "- **Workflows**: `.agents/workflows/` (multi-step orchestration)",
    `- **Subagents**: ${VENDOR_SPAWN[vendor] || "`oma agent:spawn`"}`,
    "",
    "## Per-Agent Dispatch",
    "",
    "1. Resolve `target_vendor_for_agent` from `.agents/oma-config.yaml`.",
    "2. If `target_vendor_for_agent === current_runtime_vendor`, use the runtime's native subagent path.",
    "3. If vendors differ, or native subagents are unavailable, use `oma agent:spawn` for that agent only.",
    "",
    "## Code Search",
    "",
    "Prefer **serena MCP** tools over native find/grep when locating code — they are symbol-aware and faster on large repos. Fall back to native Read / Glob / Grep only when serena is unavailable or for plain file content reads.",
    "",
    "| Task | Preferred tool |",
    "|------|----------------|",
    "| Locate a symbol definition (class / function / variable) | `find_symbol` |",
    "| Find references / callers of a symbol | `find_referencing_symbols` |",
    "| Outline a file's top-level symbols | `get_symbols_overview` |",
    "| Pattern or regex search across the codebase | `search_for_pattern` |",
    "| Find a file by name | `find_file` |",
    "| List directory contents | `list_dir` |",
    "",
    "## Workflows",
    "",
    "Execute by naming the workflow in your prompt. Keywords are auto-detected via hooks.",
    "",
    "| Workflow | File | Description |",
    "|----------|------|-------------|",
    "| orchestrate | `orchestrate.md` | Parallel subagents + Review Loop |",
    "| work | `work.md` | Step-by-step with remediation loop |",
    "| ultrawork | `ultrawork.md` | 5-Phase Gate Loop (11 reviews) |",
    "| plan | `plan.md` | PM task breakdown |",
    "| brainstorm | `brainstorm.md` | Design-first ideation |",
    "| review | `review.md` | QA audit |",
    "| debug | `debug.md` | Root cause + minimal fix |",
    "| deepsec | `deepsec.md` | Drive `oma-deepsec` end-to-end (setup / scan / pr-review / matchers / triage) |",
    "| scm | `scm.md` | SCM + Git operations + Conventional Commits |",
    "| docs | `docs.md` | Documentation drift verify + sync |",
    "| recap | `recap.md` | Daily / period AI conversation recap |",
    "| video | `video.md` | Brief → script → assets → render-spec → Remotion (oma-video) |",
    "",
    `To execute: read and follow \`.agents/workflows/{name}.md\` step by step.`,
    "",
    "## Auto-Detection",
    "",
    VENDOR_HOOKS[vendor] || "",
    "Keywords defined in `.agents/hooks/core/triggers.json` (multi-language).",
    "Persistent workflows (orchestrate, ultrawork, work) block termination until complete.",
    'Deactivate: say "workflow done".',
    "",
    "## Rules",
    "",
    "1. **Do not modify `.agents/` files** (SSOT protection).",
    "2. Workflows execute via keyword detection or explicit naming, never self-initiated.",
    "3. Response language follows `.agents/oma-config.yaml`",
    "",
  ];

  // Rules index
  if (rules.length > 0) {
    lines.push(
      "## Project Rules",
      "",
      `Read the relevant file from \`${RULES_DIR}/\` when working on matching code.`,
      "",
      "| Rule | File | Scope |",
      "|------|------|-------|",
    );

    for (const rule of rules) {
      const scope = rule.globs || (rule.alwaysApply ? "always" : "on request");
      lines.push(
        `| ${rule.name} | \`${RULES_DIR}/${rule.name}.md\` | ${scope} |`,
      );
    }

    lines.push("");
  }

  lines.push(OMA_END);
  return lines.join("\n");
}

/** Prefix used for matching any OMA:START variant. */
const OMA_START_PREFIX = "<!-- OMA:START";

/**
 * Merge OMA block into a target markdown file using markers.
 * Preserves any user content outside the OMA block.
 */
function mergeOmaBlock(filePath: string, block: string): void {
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, "utf-8");
    const startIdx = existing.indexOf(OMA_START_PREFIX);
    const endIdx = existing.indexOf(OMA_END);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + OMA_END.length);
      writeFileSync(filePath, `${before}${block}${after}`);
    } else {
      writeFileSync(filePath, `${existing.trimEnd()}\n\n${block}\n`);
    }
  } else {
    writeFileSync(filePath, `${block}\n`);
  }
}

/**
 * Generate and merge the OMA block (usage guide + rules index)
 * into the vendor's local markdown file.
 */
export function mergeRulesIndexForVendor(
  targetDir: string,
  vendor: string,
): boolean {
  const fileName = VENDOR_FILES[vendor];
  if (!fileName) return false;

  const rules = readRules(targetDir);
  const block = buildVendorBlock(vendor, rules);
  mergeOmaBlock(join(targetDir, fileName), block);
  return true;
}
